#!/bin/bash
echo  "Updating ivertion.chat, please wait."
cd  ~
cd ivertion.chat.io
git checkout master
git pull
cd backend
npm install --force
npm run build
npx sequelize db:migrate
npx sequelize db:seed
pm2 restart all
cd  ~
cd ivertion.chat.io
cd frontend
npm install --force
export NODE_OPTIONS=--openssl-legacy-provider
npx update-browserslist-db@latest
npx quasar build -P -m pwa


echo  "Update finished. Enjoy!"
